### ISSUE TITLE
Method::Execute with const parameters

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#10]
Hi @sgieseking,
thanks again for your support in my recent issues. This issue is more of a question and not really a problem:

When dealing with the Method-class
```
//! A MethodFunction is created with a function pointer that is call by the Execute method.
class MethodFunction : public Method
{
public:
    MethodFunction(Function* function, std::string const& name, std::string const& help, bool deleteOnRemove=true) :
        Method(name, help, deleteOnRemove), function_(function) {}
    virtual void Execute(Value& params, Value& result) { if (function_) function_(params, result); }
private:
    Function *function_;
};
```
I was wondering, if there would be any problem with making the "params" input of the Execute method constant:
`virtual void Execute(const Value& params, Value& result) `
If I see it correctly, params should never be changed by Execute, so this would lead to a more readable function body and self explaining code. It would require more changes to const in other functions (e.g. MethodManager::ListMethods), but I don't see any counter-argument.
After all, you have the better understanding of your class, so maybe you could tell me if I missed any point against this.

Thanks
Jan

**Comment by sgieseking** [comment]
With the way Value is defined and used, it will cause problems further down the line.  In general, it's not really necessary because params is only used for the one Execute call and then discarded.  You don't have the problem of a function accidentally/maliciously changing params and affecting something later.  Making that change would also require any existing code to update their function specification.
