### ISSUE TITLE
Growing server buffer if using notifications

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#15]
Hi,
I'm using the `Client::Notify()` functionality to send some strings to my Json-Tcp-server (I'm using a threadpool, but the behaviour is the same for single thread). On the server these strings are just printed to `std::cout`. Doing this I could observe the following behaviour: Sometimes not all messages are printed, but just the first x messages. When sending more messages later, first the missing messages are printed and the new ones are missing... This goes on and the amount of missing messages grows, but this growth is not constant.

Running in the debugger, I could track down the issue: In class `Connection `on the server, the member variable `buffer_` contains all the missing messages, so it's not a problem of the tcp-connection. If I understand the purpose of the code correctly, the problem is in function `Connection::Process()`. For notifications one never gets the state `WRITE_RESPONSE` so newMessage will be false even if other messages are in buffer.

I'm now using the hotfix
```
// When operating a thread pool, the main thread might need to continue
// to write a long response to the socket after the connection is returned
if (connectionState_ == WRITE_RESPONSE)
{
	if (!WriteResponse())
	{
		connectionState_ = CLOSE_CONNECTION;
		break;
	}
}

// Check if additional messages should be processed
newMessage = (connectionState_ == READ_HEADER) && (bufferLength_ > 1);
```
but I'm not totally sure if this is the correct fix. After all I had to use `bufferLength_ >1` instead of `>0` because otherwise one would have a infinite loop (in debugger bufferLength_ is 1 if no messages are left in the buffer, why so?). However this loop would also appear for Call(), but I'm really not sure why...

**Comment by sgieseking** [comment]
At least for a non-thread pool server, the fix would seem to be more like:

        // When operating a thread pool, the main thread will read the request
        // but stop to transfer it to a worker thread for execution
        if (executeAfterRead)
        {
            if ((connectionState_ == EXECUTE_REQUEST) && (!ExecuteRequest()))
            {
                connectionState_ = CLOSE_CONNECTION;
                break;
            }
            newMessage = (connectionState_ == READ_HEADER) && (bufferLength_ > 0);
        }
        // When operating a thread pool, the main thread might need to continue
        // to write a long response to the socket after the connection is returned
        if (connectionState_ == WRITE_RESPONSE)
        {
            if (!WriteResponse())
            {
                connectionState_ = CLOSE_CONNECTION;
                break;
            }
            newMessage = (connectionState_ == READ_HEADER) && (bufferLength_ > 0);
        }

You don't want to pull the test outside the WRITE_RESPONSE conditional.  This would keep it in the loop if part, but not all of the header, has been read.  That is probably why you needed to check for bufferLength_ > 1.  

For a tcp notification, ExecuteRequest() would change the state to READ_HEADER, so you want the same check as in the WRITE_RESPONSE conditional to continue with the processing of buffered data.  If you don't, then it has to wait for more data to arrive in order to call Process() again.

I'll have to look at the thread pool server more closely as it has a different loop.

**Comment by sgieseking** [comment]
Actually, it needs to be more like this:

        // When operating a thread pool, the main thread will read the request
        // but stop to transfer it to a worker thread for execution
        if (executeAfterRead && (connectionState_ == EXECUTE_REQUEST))
        {
            if (!ExecuteRequest())
            {
                connectionState_ = CLOSE_CONNECTION;
                break;
            }
            // for a notification over tcp, there is no data send back so check for more data to process
            newMessage = (connectionState_ == READ_HEADER) && (bufferLength_ > 0);
        }
        // When operating a thread pool, the main thread might need to continue
        // to write a long response to the socket after the connection is returned
        if (connectionState_ == WRITE_RESPONSE)
        {
            if (!WriteResponse())
            {
                connectionState_ = CLOSE_CONNECTION;
                break;
            }
            newMessage = (connectionState_ == READ_HEADER) && (bufferLength_ > 0);
        }

This should fix both standard and thread pool servers.

Since tcp notifications don't have a response, you have to make sure to not close the client before the server actually processes all of the messages or it may abort some from a closed connection.

**Comment by JanPlitzkow** [comment]
Your solution works fine for me. Thanks!
