### ISSUE TITLE
Unbind TCP-server?

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#16]
Is there any way to "unbind" a anyrpc::server for TCP without destroying it?

Background: I've a server with some attached methods. Now I would like to stop the server, so it does not listen on any port for a while. Afterwards I would like to bind it again, depending on other information to the same or another port.
Is this possible? If yes, how do I do it?
Of course one could destroy the old and initialize a totally new server, but then all attached methods have to be bound again. I'd like to avoid this.

What I've tried:
I've called StopThread(), Exit(), Shutdown() on the server but still a call of BindAndListen() leads to:
"Could not bind to spedified port: -1".
I've tried to track the error further down, but the usage of sockets in general and in this library in particular remains kind of unclear to me. After all I do not really know when to use StopThread(), Exit() and Shutdown() and in which order. Any hint on that?

Thanks again for your great library. I see, that my problem might be a little special, but I hope that you can still give some information or point me in the right direction.

**Comment by sgieseking** [comment]
Currently, there isn't a way to really unbind.  You need to close the socket and create a new one.  This could be done at the beginning of BindAndListen():

    bool Server::BindAndListen(int port, int backlog)
    {
        int result;
    
        port_ = port;
    
        socket_.Close();
        socket_.Create();
    
        // Don't block on reads/writes
        result = socket_.SetNonBlocking();

This could also be implemented by creating your own server class since socket_ is protected:

    class myServer : public AnyHttpServer
    {
        virtual bool BindAndListen(int port, int backlog = 5)
        {
            socket_.Close();
            socket_.Create();
            Server::BindAndListen(port, backlog);
        }
    }

I will need to think about any problems with just changing BindAndListen().

**Comment by sgieseking** [comment]
Regarding the use of Exit(), Shutdown(), and StopThread():

Exit():  This would be typically used within an rpc call to remotely shutdown the server.  This would process the message and then exit the work loop.  Obviously, you only implement this if it is appropriate to your application.  Looking back at this, it might be useful to provide an access function for the state of exit_.  This can also be performed with a variable outside the scope of the server.

    Server *server = new AnyHttpServer;
    server->BindAndListen(9000);
    while (!server->ShouldExit())
        Work(1000);

StopThread():  Used to shutdown a threaded server.  This could still be a single threaded server that is using the internal method to execute in a separate thread.  ThreadStarter() will call Shutdown() automatically in this case.

    Server *server = new AnyHttpServer;
    server->BindAndListen(9000);
    server->StartThread();
    // wait until you want to shutdown
    server->StopThread();

Shutdown():  This is normally only called if you need to close down all of the worker connections in a server, maybe because you will not be destroying the server immediately (which would call Shutdown()).  You might want to do this if you were changing the port binding and don't want any current connections to survive.

**Comment by JanPlitzkow** [comment]
Thanks for your explanation and help!

I've now changed my anyrpc library locally to
```
bool Server::BindAndListen(int port, int backlog)
{
    int result;

    port_ = port;

    socket_.Close();
    socket_.Create();

    // Don't block on reads/writes
    result = socket_.SetNonBlocking();
```
and 
```
bool ServerTP::BindAndListen(int port, int backlog)
{
    int result;

    // Setup the signal socket as UDP on the same port as the main socket
    serverSignal_.Close();
    serverSignal_.Create();

    // Don't block on reads/writes
    result = serverSignal_.SetNonBlocking();
```
This setup works totally fine for me, if I call `StopThread()` before a new `BindAndListen()`. 

I don't see any problems with adding this to `BindAndListen()` in general, because until now you simply can only call this function once. If I see it correctly, the change doesn't do any difference for the first call of `BindAndListen()`, but it allows consecutive ones.

But of course I will also be happy to simply define an derived class on my own. Just tell me your decision :).
