### ISSUE TITLE
Growing file descriptor while running.

### ISSUE THREAD

**Issue by wzzhan** [sgieseking/anyrpc#34]
Hi,
I'm launching the exampleServer and exampleClient provided with this project and compiled with gcc under RHEL 7.0 by these command line calls:
build/bin/exampleServer jsontcp 9000 9000
buid/bin/exampleClient
If I run the client program for 100 times, the server response correctly. However, the file descriptor occupied by the exampleServer is keep growing, which can launch following command line:
ll /proc/$(pidof exampleServer)/fd 
So If I want to open another file such a plain text file by rpc call, I may fail to open the file since the file descriptor is all occupied after many rpc call.
I wonder when the server will close the file descriptor ( socket fd ).
How can I  solve this problem?

**Comment by sgieseking** [comment]
Thanks for indicating the problem.  

It looks like the problem comes from the definition for the TcpSocket class which creates a socket in the constructor.  The Connection class constructor takes a socket file descriptor from the listening socket and assigns it to the file descriptor for it's local TcpSocket variable, but the implementation of Socket::SetFileDescriptor does not free an already allocated socket.  So it is this automatically created socket that is getting lost.  

You can fix this by adding a call to Close before the call to SetFileDescriptor.

```
Connection::Connection(SOCKET fd, MethodManager* manager) :
    manager_(manager)
{
    connectionState_ = READ_HEADER;
    lastTransactionTime_ = time(NULL);
    active_ = true;
    bufferLength_ = 0;
    contentLength_ = 0;
    request_ = 0;
    requestAllocated_ = false;
    keepAlive_ = false;
    contentAvail_ = 0;
    headerBytesWritten_ = 0;
    resultBytesWritten_ = 0;
#if defined(ANYRPC_THREADING)
    threadRunning_ = false;
#endif

    socket_.Close();
    socket_.SetFileDescriptor(fd);

    int result;
    result = socket_.SetNonBlocking();
    if (result != 0)
        log_warn("Could not set socket to non-blocking input mode: " << result);

    result = socket_.SetTcpNoDelay();
    if (result != 0)
        log_warn("Could not set socket to no delay: " << result);
}

```

You can also delete the call to automatically create the socket in the constructor for TcpSocket but there may be cases were other code assumes that a socket is created.

Another possible fix is to have SetFileDescriptor check whether the file descriptor is valid and close before assigning.  It should probably do this anyway from a defensive programming perspective.

Let me look through the rest of the code to determine the best fix.

**Comment by sgieseking** [comment]
Let me know if the fix that has been added resolves the problem.

**Comment by wzzhan** [comment]
Thanks a lot
