### ISSUE TITLE
Paser error when receive `<params />`

### ISSUE THREAD

**Issue by trunone** [sgieseking/anyrpc#9]
XmlRpc.net will send `<params />` when there is no parameters.
But AnyRPC can't parse it and return parse error.

For example:
```
<!-- Request -->
<?xml version="1.0"?>
<methodCall>
  <methodName>
    MethodName
  </methodName>
  <params/>
</methodCall>
```

```
<!-- Response -->
<?xml version="1.0" encoding="utf-8"?>
    <methodResponse>
        <fault>
            <value>
                <struct>
                    <member>
                        <name>
                            faultCode
                            </name>
                        <value>
                            <i4>
                                -32700
                                </i4>
                            </value>
                        </member>
                    <member>
                        <name>
                            faultString
                            </name>
                        <value>
                            Parse error
                            </value>
                        </member>
                    </struct>
                </value>
            </fault>
        </methodResponse>
```

**Comment by sgieseking** [comment]
I haven't seen a client that used the <params/> before.

If you want something immediate, the following change should work:

    void XmlReader::ParseParams(bool paramsParsed)
    {
        if (!paramsParsed)
        {
            int nextTag = GetNextTag();
            if (nextTag == paramsETag)
            {
                handler_->Null();
                return;
            }
            if (nextTag != paramsTag)
                anyrpc_throw(AnyRpcErrorTagInvalid, "Parse error with xml tag");
        }
    
        handler_->StartArray();
    
        for (size_t elementCount = 0; ;elementCount++)
        {
            switch (GetNextTag())
            {
                case paramTag :
                {
                    if (GetNextTag() != valueTag)
                        anyrpc_throw(AnyRpcErrorTagInvalid, "Parse error with xml tag");
                    if (elementCount != 0)
                        handler_->ArraySeparator();
                    ParseValue(true);
                    if (GetNextTag() != paramETag)
                        anyrpc_throw(AnyRpcErrorTagInvalid, "Parse error with xml tag");
                    break;
                }
                case paramsETag :
                {
                    handler_->EndArray(elementCount);
                    return;
                }
                default :
                    anyrpc_throw(AnyRpcErrorTagInvalid, "Parse error with xml tag");
            }
        }
    }

I don't totally like this because the current GetNextTag() function returns an end tag indication for both </params> and <params/>.  There really should be a third state for an empty element tag but this will require a bit more work to verify operation over the rest of the class.

**Comment by trunone** [comment]
Thanks for your response. But empty element is the standard of XML. Maybe you should consider to support it.  And I will also try to modify my client to not send any empty tag. It's really not necessary.

**Comment by sgieseking** [comment]
I'll probably check in a fix for this in the next day or two.  It seem like a lot of xmlrpc clients just send <params></params> instead of <params/> so it hasn't come up before.  Thanks for indicating the problem when using XmlRpc.net.

**Comment by sgieseking** [comment]
I checked in a change to support various forms of empty tags.  I haven't tested this against XmlRpc.net so let me know if there are still any problems.

**Comment by trunone** [comment]
OK, I will test it. Actually, I found another bug. Even I remove params tag. AnyRPC still return parse error. So you also need to consider about no params tag situation.

**Comment by sgieseking** [comment]
I'll look at that.  Are their xmlrpc client that are actually generating calls without a params tag?  Looking at the xmlrpc specification, it does have the following:

`If the procedure call has parameters, the <methodCall> must contain a <params> sub-item. The <params> sub-item can contain any number of <param>s, each of which has a <value>.`

**Comment by sgieseking** [comment]
A lot of xml-rpc implementation do their own xml parsing instead of using a standard xml parser like XmlRpc.net does.  Because of that, they don't do a lot of shortcuts.  It's also not clear from the actual xml-rpc specification if empty tags are officially allowed since they are not mentioned.

From the lines that I mentioned in from the specification, it does suggest that the params section could be eliminated entirely which I agree is currently not support by the code.  It should be an easy fix.  I'd rather be more tolerant on the reading side and more strict on the writing side to allow better interoperability.
